### ISSUE TITLE
Gerenciamento de Produtos pelas Instituições

### ISSUE THREAD

**Issue by ReginaTR** [ReginaTR/Cadastro_Doacoes#6]
- [x] #11

      - [ ] Criar o modelo Produto com os campos nome, descrição, quantidade, status, organization_id.
      - [ ]  Implementar a funcionalidade de criação de produtos vinculados à instituição logada.
      - [ ]  Criar a interface para adicionar produtos (formulário).

- [x] #12

     - [ ] Implementar a funcionalidade de edição de produtos.
     - [ ] Criar a interface para editar produtos.

- [x] #13

      - [ ]  Implementar a funcionalidade de remoção de produtos.
      - [ ] Criar botão de remoção e confirmação antes de deletar o produto.
