### ISSUE TITLE
Visualização Pública de Produtos

### ISSUE THREAD

**Issue by ReginaTR** [ReginaTR/Cadastro_Doacoes#7]
- [x] #14

  - [x] Criar uma página pública que liste todos os produtos agrupados por instituição.
  - [ ] Implementar filtros para facilitar a busca de produtos específicos.

- [x] #15

  - [x] Criar uma página de detalhes da instituição que mostre seus produtos.
  - [x] Implementar links na lista de produtos para as páginas de detalhes das instituições.
